---
- name: Classic APP Deployment Declarative model
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Device Information
    bigipmgmt: "192.168.32.100"
    user: "admin"
    password: "W3lcome098!"

    # Application Information
    partition: preprodsecureapps
    appAS3tempalte: as3_https.json
    apps:
      - name: webapp
        vsip: 10.11.3.1
        vsport: 443
        memberport: 8080
        poolname: web_pool
        webtls: webtlsabc
        members:
          - 10.1.0.1
          - 10.1.0.2
          - 10.1.0.3
    

  tasks:
    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'templates//{{ appAS3tempalte }}', split_lines=False) }}"

  
    - name: PUSH AS3
      uri:
        url: "https://{{bigipmgmt}}:443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template', 'templates/{{ appAS3tempalte }}') }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{user}}"
        password: "{{password}}"
        validate_certs: false
      delegate_to: localhost