---
- name: Upgrade BIG-IP software
  hosts: lb
  connection: local
  gather_facts: False
  vars:
    provider:
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      validate_certs: False
  vars_prompt:
    - name: version
      prompt: "Version and build from ISO"
      private: no

  tasks:
    - name: Get failover state
      bigip_command:
        commands:
          - show sys failover
        provider: "{{ provider }}" 
      register: failover_state

    - name: Display Get failover state
      debug:
        var: failover_state.stdout

    - block:
      - name: Verify running configuration of the BIG-IP
        bigip_command:
          commands:
            - load sys config verify
          provider: "{{ provider }}" 
  
      - name: Wait for configuration to finish loading
        wait_for:
          timeout: 3
        delegate_to: localhost

      - name: Get current time on BIG-IP
        command: date "+%H%M%S-%m%d%y"
        register: date

      - name: Download a new UCS
        bigip_ucs_fetch:
          src: "{{ inventory_hostname + '-' + date.stdout +  '-backup.ucs' }}"
          dest: "{{ 'files/' + inventory_hostname + '-' + date.stdout +  '-backup.ucs' }}"
          provider: "{{ provider }}"
        delegate_to: localhost

      - name: Upload image to the BIG-IP
        bigip_software_image:
         image: "{{ 'files/BIGIP-' + version  + '.iso' }}"
         provider: "{{ provider }}"
        delegate_to: localhost

      - name: Install BIG-IP software
        bigip_software_install:
          image: "{{ 'BIGIP-' + version  + '.iso' }}"
          state: installed
          volume: "HD1.2"
          provider: "{{ provider }}"
        delegate_to: localhost
        async: 45
        poll: 0

      - name: Verify the system was installed
        bigip_device_info:
          gather_subset: 
            - software-volumes
          provider: "{{ provider }}"
        register: bigip_software_install
        tags:
          - verify

      - name: Displays the device info
        debug:
          var: bigip_software_install.software_volumes
        tags:
          - verify

      when: failover_state.stdout == "*standby*"