#Specifies the current state of the node. enabled (All traffic allowed), specifies the system sends traffic to this node regardless of the node's state. disabled (Only persistent or active connections allowed), specifies the node can handle only persistent or active connections. offline (Only active connections allowed), specifies the node can handle only active connections. In all cases except absent, the node will be created if it does not yet exist.
#Be particularly careful about changing the status of a node whose FQDN cannot be resolved. These situations disable your ability to change their state to disabled or offline. They will remain in an *Unavailable - Enabled* state.

---
- name: "Node Management"
  hosts: lb
  gather_facts: false
  connection: local

  vars_prompt:

    - name: node_name
      prompt: What is the node name?
      private: no

    - name: state
      prompt: What do you want to do "disabled" or "enabled" "offline"
      private: no

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: false

    - name: Making Node changes
      bigip_node:
        state: "{{state}}"
        name: "{{node_name}}"
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Query BIG-IP facts
      f5networks.f5_modules.bigip_device_info:
        provider: "{{provider}}"
        gather_subset:
          - nodes
      register: bigip_facts


