#enabled = online 
#disabled = (Only persistent or active connections allowed),
#offline (Only active connections allowed)

---
- name: "Node Management"
  hosts: lb
  gather_facts: false
  connection: local

  vars_prompt:

    - name: node_name
      prompt: What is the node name?
      private: no

    - name: state
      prompt: What do you want to do "disabled" or "enabled" "offline"
      private: no

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: false

    - name: Making Node changes
      bigip_node:
        state: "{{state}}"
        name: "{{node_name}}"
        provider: "{{provider}}"
      delegate_to: localhost
